# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: API.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tAPI.proto\x12\rpublic.API.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x17\n\x07\x43hannel\x12\x0c\n\x04Name\x18\x01 \x01(\t\"W\n\x05\x45vent\x12\'\n\x07\x43hannel\x18\x01 \x01(\x0b\x32\x16.public.API.v1.Channel\x12%\n\x04\x44\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructB)Z\'github.com/pubsubgo/services/protos/APIb\x06proto3')



_CHANNEL = DESCRIPTOR.message_types_by_name['Channel']
_EVENT = DESCRIPTOR.message_types_by_name['Event']

@overload
class Channel(_message.Message):
	"""sylk.build generated message [None.API.v1.Channel]
	A class respresent a Channel type
	
		"""
	Name = str # type: str

	def __init__(self, Name=str):
		"""
		

		Attributes:
		----------
		Name : str
			
		"""
		pass
Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'API_pb2'
  # @@protoc_insertion_point(class_scope:public.API.v1.Channel)
  })
_sym_db.RegisterMessage(Channel)


@overload
class Event(_message.Message):
	"""sylk.build generated message [None.API.v1.Event]
	A class respresent a Event type
	
		"""
	Channel = Channel # type: Channel
	Data = google_dot_protobuf_dot_struct__pb2.Struct # type: google_dot_protobuf_dot_struct__pb2.Struct

	def __init__(self, Channel=Channel, Data=google_dot_protobuf_dot_struct__pb2.Struct):
		"""
		

		Attributes:
		----------
		Channel : Channel
			
		Data : google_dot_protobuf_dot_struct__pb2.Struct
			
		"""
		pass
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'API_pb2'
  # @@protoc_insertion_point(class_scope:public.API.v1.Event)
  })
_sym_db.RegisterMessage(Event)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/pubsubgo/services/protos/API'
  _CHANNEL._serialized_start=58
  _CHANNEL._serialized_end=81
  _EVENT._serialized_start=83
  _EVENT._serialized_end=170
# @@protoc_insertion_point(module_scope)
