# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import API_pb2 as API__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPubsub.proto\x1a\tAPI.proto\x1a\x1bgoogle/protobuf/empty.proto2~\n\x06Pubsub\x12\x37\n\x07Publish\x12\x14.public.API.v1.Event\x1a\x16.google.protobuf.Empty\x12;\n\tSubscribe\x12\x16.public.API.v1.Channel\x1a\x14.public.API.v1.Event0\x01\x42,Z*github.com/pubsubgo/services/protos/Pubsubb\x06proto3')



_PUBSUB = DESCRIPTOR.services_by_name['Pubsub']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/pubsubgo/services/protos/Pubsub'
  _PUBSUB._serialized_start=56
  _PUBSUB._serialized_end=182
# @@protoc_insertion_point(module_scope)
