from typing import Tuple, Iterator, Any
import grpc
import os
import sys
# Adding protos module path if needed
script_dir = os.path.dirname(os.path.abspath(__file__))
proto_module = os.path.join(script_dir, "protos")
if proto_module not in sys.path:
    # Insert the protos modules path at the beginning of sys.path (to give it higher priority)
    sys.path.insert(0, proto_module)
from functools import partial
from sylk.commons.interceptors import sylk_client_pre_rpc, SylkSimpleAuth
import logging
from .protos.public.bookstore.book.v1 import book_pb2 as book_v1, book_pb2_grpc as book_v1_grpc
from google.protobuf import any_pb2
from google.protobuf import struct_pb2
from google.protobuf import duration_pb2
from google.protobuf import wrappers_pb2
from google.protobuf import field_mask_pb2
from google.protobuf import empty_pb2
from google.protobuf import timestamp_pb2

# For available channel options in python visit https://github.com/grpc/grpc/blob/v1.46.x/include/grpc/impl/codegen/grpc_types.h
_CHANNEL_OPTIONS = (("grpc.keepalive_permit_without_calls", 1),
	("grpc.keepalive_time_ms", 120000),
	("grpc.keepalive_timeout_ms", 20000),
	("grpc.http2.min_time_between_pings_ms", 120000),
	("grpc.http2.max_pings_without_data", 1),)

# Global metadata
_METADATA = (('sylk-version','0.3.3'),)

# Global auth key that will be verified by sylk client
_GLOBAL_AUTH_KEY = None

# Generated thanks to [sylk.build](https://www.sylk.build)



class BookStoreService_v1:
	"""
	service class generated by sylk.build

	File: public.bookstore.book.v1.BookStoreService
	Service: BookStoreService
	Version: v1
	"""

	def __init__(self,channel: grpc.ChannelCredentials = None, client_opt = {}):
		logging.root.setLevel(client_opt.get('log_level','ERROR'))
		if channel is None:
			self.channel = grpc.insecure_channel('{0}:{1}'.format(client_opt.get('host','localhost'), client_opt.get('port',44880)),_CHANNEL_OPTIONS)
			try:
				grpc.channel_ready_future(self.channel).result(timeout=client_opt.get('timeout',10))
			except grpc.FutureTimeoutError:
				logging.error('Timedout: server seems to be offline. verify your connection configs.')
				sys.exit(1)
		else:
			self.channel = channel
		self.BookStoreService_v1_stub = book_v1_grpc.BookStoreServiceStub(self.channel)

	def ListBooks_WithCall(self, request: empty_pb2.Empty, metadata: Tuple[Tuple[str,str]] = _METADATA) -> Tuple[Iterator[book_v1.Book], Any]:
		"""sylk -  Returns: RPC output and a call object"""

		return self.BookStoreService_v1_stub.ListBooks.with_call(request,metadata=metadata)

	
	def ListBooks(self, request: empty_pb2.Empty, metadata: Tuple[Tuple[str,str]] = _METADATA) -> Iterator[book_v1.Book]:
		"""sylk - """

		return self.BookStoreService_v1_stub.ListBooks(request,metadata=metadata)

	
	def GetBook_WithCall(self, request: book_v1.GetBookRequest, metadata: Tuple[Tuple[str,str]] = _METADATA) -> Tuple[book_v1.Book, Any]:
		"""sylk -  Returns: RPC output and a call object"""

		return self.BookStoreService_v1_stub.GetBook.with_call(request,metadata=metadata)

	
	def GetBook(self, request: book_v1.GetBookRequest, metadata: Tuple[Tuple[str,str]] = _METADATA) -> book_v1.Book:
		"""sylk - """

		return self.BookStoreService_v1_stub.GetBook(request,metadata=metadata)