/* eslint-disable */
import {
  CallOptions,
  ChannelCredentials,
  Client,
  ClientOptions,
  ClientUnaryCall,
  handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  ServiceError,
  UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../google/protobuf/empty";
import { Struct } from "../../../google/protobuf/struct";

/** Generated by sylk.build, DO NOT EDIT. */

export type UnstabelServiceService = typeof UnstabelServiceService;
export const UnstabelServiceService = {
  /** [unstable.v1.UnstabelService.Shaky] - */
  shaky: {
    path: "/sylklabs.unstable.v1.UnstabelService/Shaky",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: { [key: string]: any } | undefined) =>
      Buffer.from(Struct.encode(Struct.wrap(value)).finish()),
    requestDeserialize: (value: Buffer) => Struct.unwrap(Struct.decode(value)),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface UnstabelServiceServer extends UntypedServiceImplementation {
  /** [unstable.v1.UnstabelService.Shaky] - */
  shaky: handleUnaryCall<{ [key: string]: any } | undefined, Empty>;
}

export interface UnstabelServiceClient extends Client {
  /** [unstable.v1.UnstabelService.Shaky] - */
  shaky(
    request: { [key: string]: any } | undefined,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  shaky(
    request: { [key: string]: any } | undefined,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  shaky(
    request: { [key: string]: any } | undefined,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const UnstabelServiceClient = makeGenericClientConstructor(
  UnstabelServiceService,
  "sylklabs.unstable.v1.UnstabelService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UnstabelServiceClient;
  service: typeof UnstabelServiceService;
};
