# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sylklabs.iot.v1 import iot_pb2 as sylklabs_dot_iot_dot_v1_dot_iot__pb2


class IotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/sylklabs.iot.v1.IotService/Subscribe',
                request_serializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.Topic.SerializeToString,
                response_deserializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.SensorData.FromString,
                )
        self.Publish = channel.unary_unary(
                '/sylklabs.iot.v1.IotService/Publish',
                request_serializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.PublishRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class IotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """[sylklabs.iot.v1.IotService.Subscribe] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """[sylklabs.iot.v1.IotService.Publish] - 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.Topic.FromString,
                    response_serializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.SensorData.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=sylklabs_dot_iot_dot_v1_dot_iot__pb2.PublishRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylklabs.iot.v1.IotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sylklabs.iot.v1.IotService/Subscribe',
            sylklabs_dot_iot_dot_v1_dot_iot__pb2.Topic.SerializeToString,
            sylklabs_dot_iot_dot_v1_dot_iot__pb2.SensorData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1/sylklabs.iot.v1.IotService/Publish',
            sylklabs_dot_iot_dot_v1_dot_iot__pb2.PublishRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
