# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sylklabs/iot/v1/iot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sylklabs/iot/v1/iot.proto\x12\x0fsylklabs.iot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12)\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1b.sylklabs.iot.v1.SensorData\"\x15\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\"]\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x94\x01\n\nIotService\x12\x42\n\tSubscribe\x12\x16.sylklabs.iot.v1.Topic\x1a\x1b.sylklabs.iot.v1.SensorData0\x01\x12\x42\n\x07Publish\x12\x1f.sylklabs.iot.v1.PublishRequest\x1a\x16.google.protobuf.EmptyBTZRgithub.com/sylk-build/sylk-examples/sylk-iot/services/protos/sylklabs/iot/v1;iotv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sylklabs.iot.v1.iot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZRgithub.com/sylk-build/sylk-examples/sylk-iot/services/protos/sylklabs/iot/v1;iotv1'
  _globals['_PUBLISHREQUEST']._serialized_start=108
  _globals['_PUBLISHREQUEST']._serialized_end=182
  _globals['_TOPIC']._serialized_start=184
  _globals['_TOPIC']._serialized_end=205
  _globals['_SENSORDATA']._serialized_start=207
  _globals['_SENSORDATA']._serialized_end=300
  _globals['_IOTSERVICE']._serialized_start=303
  _globals['_IOTSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
