# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/bookstore/book/v1/book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#public/bookstore/book/v1/book.proto\x12\x18public.bookstore.book.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\"\x14\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t2\xae\x01\n\x10\x42ookStoreService\x12\x45\n\tListBooks\x12\x16.google.protobuf.Empty\x1a\x1e.public.bookstore.book.v1.Book0\x01\x12S\n\x07GetBook\x12(.public.bookstore.book.v1.GetBookRequest\x1a\x1e.public.bookstore.book.v1.Bookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'public.bookstore.book.v1.book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETBOOKREQUEST']._serialized_start=94
  _globals['_GETBOOKREQUEST']._serialized_end=124
  _globals['_BOOK']._serialized_start=126
  _globals['_BOOK']._serialized_end=146
  _globals['_BOOKSTORESERVICE']._serialized_start=149
  _globals['_BOOKSTORESERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
